#!/usr/bin/env python3
# /// script
# dependencies = ["redis>=5.0"]
# ///

# DISCLAIMER: This script and the accompanying proof documentation were initially generated by Claude Opus 4.8 and
#             subsequently reviewed, validated, and refined by Burak Sezer.

"""Proof: "Millions of databases."

Creates 1,000,001 namespaces in Kronotop to demonstrate that a single cluster
can hold millions of isolated databases on top of one shared FoundationDB.

The tree is nested under Kronotop's fixed default namespace `global`, which
always exists and cannot be removed. We never create or touch `global` itself;
the `global.millions` node is the single explicit "+1" root we create.

Structure (deterministic, exactly 1,000,001 explicit NAMESPACE CREATE calls):

    global                                  (already exists, untouched)
    <root>                                  1     e.g. global.millions
    <root>.<parent-uuid>                    P     parents
    <root>.<parent-uuid>.<leaf-uuid>        P x L leaves

    total = 1 + P + (P * L)

With the defaults P=1000 and L=999 the total is 1 + 1000 + 999000 = 1,000,001.

Every namespace level is created explicitly. We never rely on the engine's
implicit creation of intermediate paths, so the counter matches the tree exactly.

Each NAMESPACE CREATE is a single, isolated FoundationDB transaction. We run a fixed pool of asyncio workers over one
multiplexed connection pool; concurrency is the number of workers.
"""

import argparse
import asyncio
import time
import uuid

import redis.asyncio as redis


class Counter:
    """Shared, single-threaded-by-asyncio progress counter."""

    def __init__(self):
        self.created = 0
        self.existed = 0
        self.failed = 0
        self.first_error = None
        self.start = time.monotonic()

    @property
    def done(self):
        return self.created + self.existed + self.failed


def record_error(counter, path, exc):
    counter.failed += 1
    if counter.first_error is None:
        counter.first_error = f"{path}: {exc}"


async def create_namespace(client, path, counter):
    try:
        await client.execute_command("NAMESPACE", "CREATE", path)
        counter.created += 1
    except redis.ResponseError as exc:
        if "already exists" in str(exc).lower():
            counter.existed += 1
        else:
            record_error(counter, path, exc)
    except Exception as exc:  # keep the worker alive on transient transport errors
        record_error(counter, path, exc)


async def worker(client, queue, counter):
    while True:
        path = await queue.get()
        try:
            if path is None:
                return
            await create_namespace(client, path, counter)
        finally:
            queue.task_done()


async def run_phase(paths, client, counter, concurrency, queue_size):
    queue = asyncio.Queue(maxsize=queue_size)
    workers = [
        asyncio.create_task(worker(client, queue, counter))
        for _ in range(concurrency)
    ]
    for path in paths:
        await queue.put(path)
    for _ in range(concurrency):
        await queue.put(None)
    await queue.join()
    await asyncio.gather(*workers)


async def reporter(counter, total, stop):
    last_done = 0
    last_t = counter.start
    while not stop.is_set():
        try:
            await asyncio.wait_for(stop.wait(), timeout=2.0)
        except asyncio.TimeoutError:
            pass
        now = time.monotonic()
        done = counter.done
        instant = (done - last_done) / max(now - last_t, 1e-9)
        overall = done / max(now - counter.start, 1e-9)
        print(
            f"  {done:>9,}/{total:,}  "
            f"created={counter.created:,} existed={counter.existed:,} "
            f"failed={counter.failed:,}  "
            f"{instant:>8,.0f}/s now  {overall:>8,.0f}/s avg",
            flush=True,
        )
        last_done, last_t = done, now


def parent_paths(root, parent_ids):
    for pid in parent_ids:
        yield f"{root}.{pid}"


def leaf_paths(root, parent_ids, leaves):
    for pid in parent_ids:
        base = f"{root}.{pid}"
        for _ in range(leaves):
            yield f"{base}.{uuid.uuid4().hex}"


async def main(args):
    total = 1 + args.parents + args.parents * args.leaves
    parent_ids = [uuid.uuid4().hex for _ in range(args.parents)]

    client = redis.Redis(
        host=args.host,
        port=args.port,
        max_connections=args.concurrency,
        decode_responses=True,
    )

    counter = Counter()
    stop = asyncio.Event()
    rep = asyncio.create_task(reporter(counter, total, stop))

    print(
        f"Creating {total:,} namespaces under '{args.root}' "
        f"({args.parents:,} parents x {args.leaves:,} leaves) "
        f"with {args.concurrency} workers -> {args.host}:{args.port}",
        flush=True,
    )

    try:
        # Phase 0: the single root namespace.
        await create_namespace(client, args.root, counter)
        # Phase 1: parents must exist before their leaves.
        await run_phase(
            parent_paths(args.root, parent_ids),
            client,
            counter,
            args.concurrency,
            args.queue_size,
        )
        # Phase 2: the bulk of the work.
        await run_phase(
            leaf_paths(args.root, parent_ids, args.leaves),
            client,
            counter,
            args.concurrency,
            args.queue_size,
        )
    finally:
        stop.set()
        await rep
        await client.aclose()

    elapsed = time.monotonic() - counter.start
    print(
        f"\nDone in {elapsed:,.1f}s ({elapsed / 60:,.1f} min)  "
        f"created={counter.created:,} existed={counter.existed:,} "
        f"failed={counter.failed:,}  "
        f"avg={counter.done / max(elapsed, 1e-9):,.0f}/s",
        flush=True,
    )
    if counter.first_error:
        print(f"first error: {counter.first_error}", flush=True)
    if counter.done != total:
        print(f"WARNING: processed {counter.done:,} != expected {total:,}", flush=True)


def parse_args():
    p = argparse.ArgumentParser(description="Create millions of namespaces in Kronotop.")
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=5484)
    p.add_argument("--root", default="global.millions")
    p.add_argument("--parents", type=int, default=1000)
    p.add_argument("--leaves", type=int, default=999)
    p.add_argument("--concurrency", type=int, default=200)
    p.add_argument("--queue-size", type=int, default=10000)
    return p.parse_args()


if __name__ == "__main__":
    asyncio.run(main(parse_args()))
