/*
 * Copyright (c) 2023-2026 Burak Sezer
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kronotop.bucket.index;

import com.kronotop.internal.JSONUtil;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class VectorIndexDefinitionTest {

    @Test
    void shouldCreateWithAutoName() {
        // Behavior: Creating with a name generated by VectorIndexNameGenerator produces the expected name.
        String name = VectorIndexNameGenerator.generate("embedding", 1536, DistanceFunction.COSINE);
        VectorIndexDefinition def = VectorIndexDefinition.create(name, "embedding", 1536, DistanceFunction.COSINE, IndexStatus.WAITING);
        assertEquals("vector:embedding.dimensions:1536.distance:COSINE", def.name());
        assertEquals("embedding", def.selector());
        assertEquals(1536, def.dimensions());
        assertEquals(DistanceFunction.COSINE, def.distance());
        assertEquals(IndexStatus.WAITING, def.status());
    }

    @Test
    void shouldCreateWithExplicitName() {
        // Behavior: Creating with an explicit name uses that name instead of auto-generating.
        VectorIndexDefinition def = VectorIndexDefinition.create("my_vec_idx", "embedding", 1536, DistanceFunction.COSINE, IndexStatus.WAITING);
        assertEquals("my_vec_idx", def.name());
        assertEquals("embedding", def.selector());
        assertEquals(1536, def.dimensions());
        assertEquals(DistanceFunction.COSINE, def.distance());
        assertEquals(IndexStatus.WAITING, def.status());
    }

    @Test
    void shouldRejectZeroDimensions() {
        // Behavior: Zero dimensions are rejected with an error.
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                VectorIndexDefinition.create("test", "embedding", 0, DistanceFunction.COSINE, IndexStatus.WAITING)
        );
        assertEquals("Vector index dimensions must be >= 1, got 0", ex.getMessage());
    }

    @Test
    void shouldRejectNegativeDimensions() {
        // Behavior: Negative dimensions are rejected with an error.
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                VectorIndexDefinition.create("test", "embedding", -1, DistanceFunction.COSINE, IndexStatus.WAITING)
        );
        assertEquals("Vector index dimensions must be >= 1, got -1", ex.getMessage());
    }

    @Test
    void shouldUpdateStatus() {
        // Behavior: updateStatus returns a new instance with the given status.
        VectorIndexDefinition def = VectorIndexDefinition.create("test", "embedding", 1536, DistanceFunction.COSINE, IndexStatus.WAITING);
        VectorIndexDefinition updated = def.updateStatus(IndexStatus.READY);
        assertEquals(IndexStatus.READY, updated.status());
        assertEquals(def.id(), updated.id());
    }

    @Test
    void shouldBlockStatusChangeFromDropped() {
        // Behavior: A DROPPED index cannot transition to any other status.
        VectorIndexDefinition def = VectorIndexDefinition.create("my_vec_idx", "embedding", 1536, DistanceFunction.COSINE, IndexStatus.WAITING);
        VectorIndexDefinition dropped = def.updateStatus(IndexStatus.DROPPED);

        IllegalStateException ex = assertThrows(IllegalStateException.class, () ->
                dropped.updateStatus(IndexStatus.READY)
        );
        assertEquals("Index 'my_vec_idx' is already dropped and its status cannot be modified.", ex.getMessage());
    }

    @Test
    void shouldEncodeDecode() {
        // Behavior: A VectorIndexDefinition should survive JSON round-trip serialization.
        VectorIndexDefinition def = VectorIndexDefinition.create("my_vec_idx", "embedding", 1536, DistanceFunction.EUCLIDEAN, IndexStatus.WAITING);
        byte[] data = JSONUtil.writeValueAsBytes(def);

        VectorIndexDefinition decoded = JSONUtil.readValue(data, VectorIndexDefinition.class);
        assertEquals(def.id(), decoded.id());
        assertEquals(def.name(), decoded.name());
        assertEquals(def.selector(), decoded.selector());
        assertEquals(def.dimensions(), decoded.dimensions());
        assertEquals(def.distance(), decoded.distance());
        assertEquals(def.status(), decoded.status());
    }
}
